version: '3'

services:
  mysql:
    container_name: mysql_for_index
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: youn
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql-init-file/:/docker-entrypoint-initdb.d/
    command:
      [
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
      ]
volumes:
  mysql: